version: '3.5'

services:
  db:
    build: './sql'
    volumes:
      - db-volumes:/var/lib/mysql
  
  spring-back:
    build: './back-end'
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/workoutrecorder?autoReconect=true
      - SPRING_DATASOURCE_USERNAME=WORKOUT
      - SPRING_DATASOURCE_PASSWORD=WORKOUT1234_
    restart: always
    depends_on:
      - "db"
   
  angular-front:
    build: './front-end'
    ports:
      - "4200:80"
  
volumes:
  db-volumes: